[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
; upload_port = COM7
upload_speed = 115200
board_build.partitions = huge_app.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    bblanchon/ArduinoJson@^6
    adafruit/Adafruit SSD1306@^2
    adafruit/Adafruit GFX Library@^1
